displayName: MaxMind GeoIP with Coordinates

summary: 'Getting data from MaxMind GeoIP databases and pass it downstream via HTTP request headers.'

type: middleware

import: github.com/Maronato/traefikgeoip2

testData:
  dbPath: 'GeoLite2-Country.mmdb'